//try, catch,finally, throw
try{
    //code test
    alert("HI everyone");
    // alert(x);
    alert("Bye");
}
catch(err){
    //handle error
    alert("there is error in the code");
    console.log(err);
    // console.log(err.name);
    // console.log(err.massage);
}finally{
    alert("Bye Everyone")
}



// alert("HI everyone");
// alert(x); //the error is here
// alert("Bye");